# Generated by Django 4.2.27 on 2026-01-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='deadline',
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
